<a href="https://colab.research.google.com/github/LiaDahlia/UAS-Machine-Learning/blob/main/Soal%20No.%201%20UAS%20Machine%20Learning%20(2018102030%20Lia%20Dahlia).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Dataset
jk =['Laki-laki','Laki-laki', 'Perempuan', 'Perempuan', 'Laki-laki', 'Laki-laki', 'Perempuan','Perempuan', 'Laki-laki', 'Perempuan']
biaya =['Murah', 'Murah', 'Murah','Murah','Murah', 'Standar', 'Standar', 'Mahal', 'Mahal','Mahal']
income =['Rendah','Sedang','Sedang', 'Rendah', 'Sedang','Sedang','Sedang', 'Tinggi', 'Sedang', 'Tinggi']
transportasi =['Bus', 'Bus', 'Kereta Api', 'Bus', 'Bus', 'Kereta Api','Kereta Api', 'Mobil', 'Mobil','Mobil' ]

tujuan =['No','Yes','Yes','No','Yes','No','Yes','Yes','No', 'No']  

In [4]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
#Convert label string ke numbers
jk_encoded=le.fit_transform(jk)
print (jk_encoded)

[0 0 1 1 0 0 1 1 0 1]


In [6]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
label = preprocessing.LabelEncoder()
#Convert label string ke numbers
biaya_encoded=label.fit_transform(biaya)
print (biaya_encoded) 

income_encoded=label.fit_transform(income)
print (income_encoded)

transportasi_encoded=label.fit_transform(transportasi)
print (transportasi_encoded)

tujuan_encoded=label.fit_transform(tujuan)
print (tujuan_encoded)

[1 1 1 1 1 2 2 0 0 0]
[0 1 1 0 1 1 1 2 1 2]
[0 0 1 0 0 1 1 2 2 2]
[0 1 1 0 1 0 1 1 0 0]


In [7]:
print ("Jenis Kelamin             :",jk_encoded)
print ("Biaya Perjalanan(Rp)/km   :",biaya_encoded)
print ("Income Level              :",income_encoded)
print ("Model Transportasi        :",transportasi_encoded)
print ("Tujuan                    :",tujuan_encoded)

Jenis Kelamin             : [0 0 1 1 0 0 1 1 0 1]
Biaya Perjalanan(Rp)/km   : [1 1 1 1 1 2 2 0 0 0]
Income Level              : [0 1 1 0 1 1 1 2 1 2]
Model Transportasi        : [0 0 1 0 0 1 1 2 2 2]
Tujuan                    : [0 1 1 0 1 0 1 1 0 0]


In [8]:
#Combining fitur-fitur yang ada
features=zip(jk_encoded,biaya_encoded,income_encoded,transportasi_encoded)
features=list(features)
print (tuple(features))

((0, 1, 0, 0), (0, 1, 1, 0), (1, 1, 1, 1), (1, 1, 0, 0), (0, 1, 1, 0), (0, 2, 1, 1), (1, 2, 1, 1), (1, 0, 2, 2), (0, 0, 1, 2), (1, 0, 2, 2))


In [10]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Panggil Gaussian Classifier
model = GaussianNB()

#Train model untuk data training
model.fit(features,tujuan)
#Model.fit(features,label.reshape(-1,1))

#Peridiction Output
predicted = model.predict([[1,2,0,0]]) #1 : perempuan, 2: Standar, 0: Rendah, 0 : Bus
print ("Hasil Perdiksi:", predicted)

Hasil Perdiksi: ['No']
